<?php
// @codingStandardsIgnoreFile

/**
 * Edit customer address template
 *
 * @var $block \Magento\Customer\Block\Address\Edit
 */
?>
<form class="form-address-edit" action="<?php echo $block->getSaveUrl() ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php echo __('* Required Fields') ?>">
    <fieldset class="fieldset">
        <legend class="legend"><span><?php echo __('Contact Information') ?></span></legend><br>
        <?php echo $block->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php echo $block->getErrorUrl() ?>">
        <?php echo $block->getNameBlockHtml() ?>
        <div class="field company">
            <label class="label" for="company"><span><?php echo __('Company') ?></span></label>
            <div class="control">
                <input type="text" name="company" id="company" title="<?php echo __('Company') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
            <div class="control">
                <input type="text" name="telephone" value="<?php echo $block->escapeHtml($block->getAddress()->getTelephone()) ?>" title="<?php echo __('Phone Number') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>" id="telephone">
            </div>
        </div>
        <div class="field fax">
            <label class="label" for="fax"><span><?php echo __('Fax') ?></span></label>
            <div class="control">
                <input type="text" name="fax" id="fax" title="<?php echo __('Fax') ?>" value="<?php echo $block->escapeHtml($block->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset" data-address-fieldset>
        <legend class="legend"><span><?php echo __('Address') ?></span></legend><br>
        <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

        <div class="field country required countryVal">
            <label class="label" for="country"><span><?php echo __('Country') ?></span></label>
            <div class="control">
                <?php echo $block->getCountryHtmlSelect() ?>
            </div>
        </div>

        <div class="field postcodeApi">
            <label for="address_finder" class="label"><span><?php echo __('Address Finder') ?></span></label>
            <input type="text" class="input-text" name="address_finder" id="address_finder" />
            <div class="control">
                <div class="show_address"></div>
                <button class="button action primary address-btn" type="button"><?php echo __('Find address') ?></button>
            </div>
        </div>

        <div class="field street required">
            <label for="street_1" class="label"><span><?php echo __('Street Address') ?></span></label>
            <div class="control">
                <input type="text" name="street[]" data-autocomplete value="<?php echo $block->escapeHtml($block->getStreetLine(1)) ?>" title="<?php echo __('Street Address') ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>"  />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?php echo $_i+1 ?>">
                                <span><?php echo __('Street Address %1', $_i+1) ?></span>
                            </label>
                            <div class="control">
                                <input type="text" name="street[]" data-autocomplete value="<?php echo $block->escapeHtml($block->getStreetLine($_i+1)) ?>" title="<?php echo __('Street Address %1', $_i+1) ?>" id="street_<?php echo $_i+1 ?>" class="input-text <?php echo $_streetValidationClass ?>">
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?php echo __('VAT Number') ?></span></label>
                <div class="control">
                    <input type="text" name="vat_id" value="<?php echo $block->escapeHtml($block->getAddress()->getVatId()) ?>" title="<?php echo __('VAT Number') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>" id="vat_id">
                </div>
            </div>
        <?php endif; ?>
        <div class="field city required">
            <label class="label" for="city"><span><?php echo __('City') ?></span></label>
            <div class="control">
                <input type="text" name="city" data-autocomplete value="<?php echo $block->escapeHtml($block->getAddress()->getCity()) ?>" title="<?php echo __('City') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>" id="city">
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region"><span><?php echo __('State/Province') ?></span></label>
            <div class="control">
                <input type="text" id="region" name="region" data-autocomplete value="<?php echo $block->escapeHtml($block->getRegion()) ?>"  title="<?php echo __('State/Province') ?>" class="input-text <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?php echo(!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : '';?>/>
            </div>
        </div>
        <div class="field zip required">
            <label class="label" for="zip"><span><?php echo __('Zip/Postal Code') ?></span></label>
            <div class="control">
                <input type="text" name="postcode" data-autocomplete value="<?php echo $block->escapeHtml($block->getAddress()->getPostcode()) ?>" title="<?php echo __('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
            </div>
        </div>


        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info"><?php echo __("It's a default billing address.") ?></div>
        <?php elseif ($block->canSetAsDefaultBilling()): ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing"><span><?php echo __('Use as my default billing address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info"><?php echo __("It's a default shipping address.") ?></div>
        <?php elseif ($block->canSetAsDefaultShipping()): ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping"><span><?php echo __('Use as my default shipping address') ?></span></label>
            </div>
        <?php else: ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" data-action="save-address" title="<?php echo __('Save Address') ?>">
                <span><?php echo __('Save Address') ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php echo __('Go back') ?></span></a>
        </div>
    </div>
</form>

<script type="text/javascript">
require(['jquery'], function($){
   
   $('body').on('click','.address-ul li', function() {
        var id = $(this).attr('id');
        $('body').loader('show');
        var apiUrl = "https://services.3xsoftware.co.uk/Search/ById/json?username=" + encodeURI(window.UserName)
            + "&key=" + encodeURI(window.ApiKey)
            + "&id=" + encodeURI(id);
        $.ajax({
                url: apiUrl,
                type: 'GET',
                dataType: 'jsonp',
                cors: true ,
                contentType:'application/json',
                secure: true,
                showLoader: true,
                headers: {
                  'Access-Control-Allow-Origin': '*',
                },
                beforeSend: function (xhr) {
                  xhr.setRequestHeader ("Authorization", "Basic " + btoa(""));
                },
            success: function (data) {
                var street = '';
                var _data = data.Address;
                if(_data.StreetAddress2 != null){
                	street = _data.StreetAddress2;
                }
                if(_data.StreetAddress3 != null){
                	street += _data.StreetAddress3;
                }
                $('.form-address-edit #street_1').val(_data.StreetAddress1).trigger('keyup');
                $('.form-address-edit #street_2').val(street).trigger('keyup');
                $('.form-address-edit input[name="city"]').val(_data.PostTown).trigger('keyup');
                $('.form-address-edit input[name="company"]').val(_data.Company).trigger('keyup');
                $('.form-address-edit input[name="postcode"]').val(_data.Postcode).trigger('keyup');
                $('.form-address-edit select[name="country_id"]').val('GB').trigger('change');
                $('.form-address-edit input[name="region"]').val(_data.County).trigger('keyup');
                $('body').loader('hide');
            },
            error: function (data) {
                $(data).appendTo('.show_address');
                $('body').loader('hide');
                console.error(data);
            }
        }); 
   });
   
   $('.address-btn').click(function() {
        var postcode = $('#address_finder').val();
        if (!postcode) {
            $('.show_address').html('Please enter a postcode!');
            $('.show_address').css('color','red');
        } else {
            //Start loader
            $('body').loader('show');
            var strUrl = "https://services.3xsoftware.co.uk/Search/ByPostcode/json?username=" + encodeURI(window.UserName)
                + "&key=" + encodeURI(window.ApiKey)
                + "&postcode=" + encodeURI(postcode);
            $.ajax({
                url: strUrl,
                type: 'GET',
                dataType: 'jsonp',
                cors: true ,
                contentType:'application/json',
                secure: true,
                showLoader: true,
                headers: {
                  'Access-Control-Allow-Origin': '*',
                },
                beforeSend: function (xhr) {
                  xhr.setRequestHeader ("Authorization", "Basic " + btoa(""));
                },
                success: function (data) {
                    var ul,li;
                    ul = $('<ul>', {'class': 'address-ul'});
                    ul.empty();
                    console.log({ summaries: data.Summaries, data});
                    $.each(data.Summaries, function() {
                        li = $('<li>', {
                            'id': this.Id,
                            'class': 'address-li'
                        }).text(this.StreetAddress+', '+this.Place).appendTo(ul);
                    });
                    $(ul).appendTo('.show_address');
                    $('body').loader('hide');
                },
                error: function (data){
                  console.log(data);
                }
            });
        }
    });
});
</script>
